create table if not exists public.jlpt_vocabulary (
  id bigint generated by default as identity primary key,
  word text not null,
  meaning text not null,
  furigana text not null default '',
  romaji text not null default '',
  level smallint not null check (level between 1 and 5),
  created_at timestamptz not null default now(),
  unique (word, meaning, level)
);

create index if not exists jlpt_vocabulary_level_idx
  on public.jlpt_vocabulary (level);

alter table public.jlpt_vocabulary enable row level security;

create policy "JLPT vocabulary is publicly readable"
  on public.jlpt_vocabulary
  for select
  to anon, authenticated
  using (true);
